---
- name:                 'check configuration file freshness'
  shell:                fresh_content="$(sed 's#^auth-user-pass.*$#auth-user-pass /storage/nordvpn_up#' /etc/openvpn/nordvpn/ovpn_udp/{{ vpn_server }}.udp.ovpn; printf z)"; fresh_content="${fresh_content%z}"; current_content="$(cat /etc/openvpn/nordvpn.conf; printf z)"; current_content="${current_content%z}"; test "${fresh_content}" = "${current_content}"
  failed_when:          false
  register:             check_conf_freshness_result
  changed_when:         0 != check_conf_freshness_result.rc
