---
- include_tasks:                '../tasks/install_files.yml'
  vars:
    install_files:              "{{ install_files_while_down }}"
- include_tasks:                '../tasks/stop_services.yml'
  vars:
    stop_services:              "{{ restart_services }}"
  when:                         install_files_result is defined and install_files_result.changed
- include_tasks:                '../tasks/install_files.yml'
  vars:
    install_files:              "{{ install_files_while_down }}"
  when:                         stop_services_result is defined and stop_services_result.changed
- include_tasks:                '../tasks/start_services.yml'
  vars:
    start_services:             "{{ restart_services }}"
  when:                         stop_services_result is defined and stop_services_result.changed

