---
- include_vars:         "../../../sensitive-ansible/inventory/host_vars/{{ inventory_hostname }}.yml"
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/disable_services.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/install_files_ignore_result.yml'
- include_tasks:        '../tasks/lines_in_files.yml'
- include_tasks:        '../tasks/sync_dirs.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        'check_conf_freshness.yml'
- include_tasks:        '../tasks/remove_files.yml'
  when:                 check_conf_freshness_result.changed
- include_tasks:        '../tasks/shell_commands.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 sync_dirs_result.changed
                        or lines_in_files_result.changed
                        or remove_files_result.changed
                        or install_files_result.changed
# Reboot for firewall rules.
- include_tasks:        '../tasks/reboot.yml'
  when:                 install_files_result.changed
