---
- include:              '../tasks/dependencies.yml'
- include_vars:         "../../../sensitive-ansible/inventory/host_vars/{{ inventory_hostname }}.yml"
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/disable_services.yml'
- include:              '../tasks/template_files.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/install_files_ignore_result.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/sync_dirs.yml'
- include:              '../tasks/symlinks.yml'
- include:              'check_conf_freshness.yml'
- include:              '../tasks/remove_files.yml'
  when:                 check_conf_freshness_result.changed
- include:              '../tasks/shell_commands.yml'
- include:              '../tasks/restart_services.yml'
  when:                 sync_dirs_result.changed
                        or lines_in_files_result.changed
                        or remove_files_result.changed
                        or install_files_result.changed
# Reboot for firewall rules.
- include:              '../tasks/reboot.yml'
  when:                 install_files_result.changed
